version: "2.2"
services:
  openbabel:
    #    build: ./docker
    image: ghcr.io/cheminfo/openbabel-docker:head
    restart: always
    ulimits:
      core: 0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - 127.0.0.1:20808:20808
